const INVALID_DATA_ERROR = 400;
const AUTHORIZATION_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const NOT_FOUND_ERROR = 404;
const DATA_CONFLICT_ERROR = 409;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  INVALID_DATA_ERROR,
  AUTHORIZATION_ERROR,
  FORBIDDEN_ERROR,
  NOT_FOUND_ERROR,
  DATA_CONFLICT_ERROR,
  INTERNAL_SERVER_ERROR,
};
